services:
  laravel_frankenphp:
    container_name: laravel_frankenphp
    image: image_laravel_frankenphp
    build:
      context: .
    ports:
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - postgres_db
  
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hybrix
      POSTGRES_USER: hybrix_user
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: